spring:
  application:
    name: ProjectIAMService
  datasource:
    url: jdbc:postgresql://localhost:5432/IAM_Service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update


