spring:
  application:
    name: ProjectIAMService
  datasource:
    url: jdbc:postgresql://localhost:5432/IAM_Service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: trace
debug: true
service:
  mail:
    from: hellohoangson@gmail.com
    sendgrid:
      apiKey: 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
#redis:
#  host: localhost
#  port: 6379


