spring:
  application:
    name: ProjectIAMService
  datasource:
    url: jdbc:postgresql://localhost:5432/IAM_Service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: trace
debug: true
service:
  mail:
    from: hellohoangson@gmail.com
    sendgrid:
      apiKey: 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


